# Generated by Django 5.1.7 on 2025-03-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20250322_2005'),
    ]

    operations = [
    ]
