# Generated by Django 5.1.7 on 2025-03-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20250322_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
